name: Compile

on:
  push:
    branches:
      - fix_fs_perm_denied
  pull_request:
    branches:
      - fix_fs_perm_denied
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang
          sudo apt-get install -y wget unzip
          
      - name: Download and install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r21e
          export PATH=$PATH:$ANDROID_NDK_HOME
          
      - name: Compile code
        run: |
          clang++ -static-libstdc++ -w -Wno-c++11-narrowing -DUSE_STANDALONE -I$ANDROID_NDK_HOME/sysroot/usr/include -o poc poc.cpp -llog
