name: Compile

on:
  push:
    branches:
      - fix_fs_perm_denied
  pull_request:
    branches:
      - fix_fs_perm_denied
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang
          sudo apt-get install -y wget unzip

      - name: Download and install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          export ANDROID_NDK_HOME=$PWD/android-ndk-r25b
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
          
      - name: Compile code for aarch64
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_HOME }}
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ \
            -static-libstdc++ -w -Wno-c++11-narrowing -DUSE_STANDALONE \
            --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
            -o poc poc.cpp -llog

      - name: Upload compiled binary
        uses: actions/upload-artifact@v2
        with:
          name: poc
          path: ./poc
